# Generated by Django 5.1.7 on 2025-05-11 17:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=10, unique=True, verbose_name='手機')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子信箱')),
                ('email_is_active', models.BooleanField(default=False, null=True, verbose_name='信箱狀態')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='收件地址標題')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('place', models.CharField(max_length=50, verbose_name='詳細地址')),
                ('mobile', models.CharField(max_length=10, verbose_name='手機')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='市話')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子信箱')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='邏輯刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='areas.region', verbose_name='城市')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='areas.region', verbose_name='行政區')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='areas.region', verbose_name='郵遞區號')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='所屬用戶')),
            ],
            options={
                'verbose_name': '用戶收件地址',
                'verbose_name_plural': '用戶收件地址',
                'db_table': 'useraddresses',
                'ordering': ['updated_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_user', to='users.useraddress', verbose_name='預設收件地址'),
        ),
    ]
