# Generated by Django 5.1.7 on 2025-05-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-updated_at'], 'verbose_name': '用戶收件地址', 'verbose_name_plural': '用戶收件地址'},
        ),
    ]
