# Generated by Django 5.1.7 on 2025-05-08 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='信箱狀態'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='收件地址標題')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('place', models.CharField(max_length=50, verbose_name='詳細地址')),
                ('mobile', models.CharField(max_length=10, verbose_name='手機')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='市話')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子信箱')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='邏輯刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='useraddresses', to='areas.region', verbose_name='郵遞區號')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='所屬用戶')),
            ],
            options={
                'verbose_name': '用戶收件地址',
                'verbose_name_plural': '用戶收件地址',
                'db_table': 'useraddresses',
                'ordering': ['updated_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_user', to='users.useraddress', verbose_name='預設收件地址'),
        ),
    ]
