# Generated by Django 5.1.7 on 2025-05-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='縣市區或郵遞區號')),
                ('level', models.CharField(choices=[('city', '縣市'), ('district', '區'), ('postal_code', '郵遞區號')], max_length=50, verbose_name='區域層級')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='areas.region', verbose_name='上級區域')),
            ],
            options={
                'verbose_name': '台灣行政區域',
                'verbose_name_plural': '台灣行政區域',
            },
        ),
    ]
