# Generated by Django 5.1.7 on 2025-05-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='desc_detail',
            field=models.ImageField(default='', upload_to='goods/', verbose_name='詳細介紹'),
        ),
    ]
