# Generated by Django 5.2.1 on 2025-07-07 11:15

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='', verbose_name='Logo圖片'),
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='', verbose_name='圖片'),
        ),
    ]
