# Generated by Django 5.1.7 on 2025-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_desc_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('image1', models.ImageField(upload_to='goods/')),
                ('image2', models.ImageField(upload_to='orders/')),
            ],
            options={
                'db_table': 'test_image_upload',
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='desc_detail',
        ),
    ]
