# Generated by Django 5.1.7 on 2025-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_test_remove_goods_desc_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image2',
        ),
        migrations.AlterField(
            model_name='test',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
    ]
