# Generated by Django 5.2 on 2025-05-19 13:13

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_delete_test_goods_desc_detail_goods_desc_pack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('image1', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='goods/')),
            ],
            options={
                'db_table': 'test_image_upload',
            },
        ),
    ]
