# b2cmall/deploy/Dockerfile.nginx
FROM nginx:alpine

# 複製整個前端專案到 nginx 預設網站根目錄
COPY ./ /usr/share/nginx/html/

# 複製自訂 nginx 設定檔到容器中，故蓋掉容器預設的設定檔
COPY ./deploy/nginx.conf /etc/nginx/conf.d/default.conf

# 容器對外開放 80 埠
EXPOSE 80

 # 前台啟動 nginx，容器不會退出
CMD ["nginx", "-g", "daemon off;"]
 