########################################
# 前端 www.meiduo.site
########################################
server {
    listen 80;
    server_name www.meiduo.site;

    index index.html;

    # 訪問根目錄或其他靜態資源
    location / {
        # 先找 /app/generated_html 裡的檔案
        root /app/generated_html;
        try_files $uri $uri/ @frontend;
    }

    # fallback 到前端原本靜態檔案
    location @frontend {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
    }

    # /goods/ 優先讀 Celery 生成的新商品頁，讀不到則fallback到原始目錄
    location /goods/ {
        
        alias /app/generated_html/goods/;
        try_files $uri @fallback_goods;

        # 避免瀏覽器快取
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # fallback 到前端原始 goods
    location @fallback_goods {
        root /usr/share/nginx/html;
        index index.html;
    }
}

########################################
# 後端 api.meiduo.site
########################################
server {
    listen 80;
    server_name api.meiduo.site;

    # 提供 Django collectstatic 輸出的靜態檔案
    location /static/ {
        alias /app/static/;  # 訪問static/，會到/app/static/找檔案
    }

    # (一般建議) 上傳媒體檔案(本專案走django-storages=S3，故不用)
    # location /media/ {
    #     alias /app/media/;
    # }

    # 所有 API
    location / {
        proxy_pass http://backend:8000; # 將請求轉給django容器
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
