# Generated by Django 5.2.1 on 2025-07-07 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_alter_brand_logo_alter_skuimage_image'),
        ('users', '0002_alter_useraddress_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('total_count', models.IntegerField(default=1, verbose_name='訂購商品總數')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品總價')),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='運費')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '貨到付款'), (2, '線上支付')], default=1, verbose_name='支付方式')),
                ('status', models.SmallIntegerField(choices=[(1, '待付款'), (2, '待出貨'), (3, '待收貨'), (4, '待評價'), (5, '已完成'), (6, '已取消')], default=1, verbose_name='訂單狀態')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.useraddress', verbose_name='收件地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '訂單基本資訊',
                'verbose_name_plural': '訂單基本資訊',
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('count', models.IntegerField(default=1, verbose_name='商品數量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('comment', models.TextField(blank=True, default='', verbose_name='評價')),
                ('score', models.SmallIntegerField(blank=True, choices=[(0, '0星'), (1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=None, null=True, verbose_name='滿意度評分')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名評價')),
                ('is_commented', models.BooleanField(default=False, verbose_name='是否已評價')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.sku', verbose_name='訂單商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_goods', to='orders.orderinfo', verbose_name='所屬訂單')),
            ],
            options={
                'verbose_name': '訂單商品',
                'verbose_name_plural': '訂單商品',
                'db_table': 'order_goods',
            },
        ),
        migrations.AddIndex(
            model_name='orderinfo',
            index=models.Index(fields=['user', 'status'], name='order_info_user_id_514280_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinfo',
            index=models.Index(fields=['status'], name='order_info_status_0409d0_idx'),
        ),
    ]
