# Generated by Django 5.1.7 on 2025-05-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('key', models.CharField(max_length=50, verbose_name='類別鍵名')),
            ],
            options={
                'verbose_name': '廣告分組類',
                'verbose_name_plural': '廣告分組類',
                'db_table': 'tb_content_category',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('url', models.CharField(max_length=300, verbose_name='內容連結')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='圖片')),
                ('text', models.TextField(blank=True, null=True, verbose_name='內容')),
                ('sequence', models.IntegerField(verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='是否顯示')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contents.contentcategory', verbose_name='類別')),
            ],
            options={
                'verbose_name': '廣告內容',
                'verbose_name_plural': '廣告內容',
                'db_table': 'tb_content',
            },
        ),
    ]
