# Generated by Django 5.2.1 on 2025-07-23 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECPayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('status', models.SmallIntegerField(choices=[(0, '待付款'), (1, '已付款'), (2, '付款失敗')], default=0, verbose_name='綠界訂單狀態')),
                ('merchant_trade_no', models.CharField(max_length=32, unique=True, verbose_name='特店訂單編號（MerchantTradeNo）')),
                ('trade_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='綠界交易編號（TradeNo）')),
                ('rtn_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='交易結果代碼（RtnCode）')),
                ('rtn_msg', models.TextField(blank=True, null=True, verbose_name='交易結果訊息（RtnMsg）')),
                ('payment_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='付款方式（PaymentType）')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='付款完成時間（PaymentDate）')),
                ('payment_type_charge_fee', models.IntegerField(blank=True, null=True, verbose_name='手續費（PaymentTypeChargeFee）')),
                ('trade_amt', models.IntegerField(verbose_name='實際付款金額（TradeAmt）')),
                ('simulate_paid', models.BooleanField(default=False, verbose_name='是否為模擬付款（SimulatePaid）')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecpay_transactions', to='orders.orderinfo', verbose_name='關聯訂單')),
            ],
            options={
                'verbose_name': '綠界交易紀錄',
                'verbose_name_plural': '綠界交易紀錄',
                'ordering': ['-create_time'],
            },
        ),
    ]
