# Generated by Django 5.1.7 on 2025-04-21 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], help_text='例如 Google 或 Facebook', max_length=20, verbose_name='登入平台')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='唯一識別碼')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='信箱')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='所屬用戶')),
            ],
            options={
                'verbose_name': '社交帳號',
                'verbose_name_plural': '社交帳號',
                'db_table': 'user_social_account',
                'ordering': ['-create_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
