# Generated by Django 5.1.7 on 2025-04-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersocialaccount',
            table=None,
        ),
    ]
